/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Fri Apr 13 20:50:24 2018. */

#ifndef PB_FLOOR_PB_H_INCLUDED
#define PB_FLOOR_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _TempSet {
    int32_t zone_1;
    int32_t zone_2;
    int32_t zone_3;
    int32_t zone_4;
    int32_t zone_5;
    int32_t zone_6;
/* @@protoc_insertion_point(struct:TempSet) */
} TempSet;

typedef struct _State {
    int32_t temp1;
    int32_t temp2;
    TempSet tempSet;
    TempSet tempActual;
/* @@protoc_insertion_point(struct:State) */
} State;

/* Default values for struct fields */

/* Initializer values for message structs */
#define TempSet_init_default                     {0, 0, 0, 0, 0, 0}
#define State_init_default                       {0, 0, TempSet_init_default, TempSet_init_default}
#define TempSet_init_zero                        {0, 0, 0, 0, 0, 0}
#define State_init_zero                          {0, 0, TempSet_init_zero, TempSet_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define TempSet_zone_1_tag                       1
#define TempSet_zone_2_tag                       2
#define TempSet_zone_3_tag                       3
#define TempSet_zone_4_tag                       4
#define TempSet_zone_5_tag                       5
#define TempSet_zone_6_tag                       6
#define State_temp1_tag                          1
#define State_temp2_tag                          2
#define State_tempSet_tag                        3
#define State_tempActual_tag                     4

/* Struct field encoding specification for nanopb */
extern const pb_field_t TempSet_fields[7];
extern const pb_field_t State_fields[5];

/* Maximum encoded size of messages (where known) */
#define TempSet_size                             66
#define State_size                               158

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FLOOR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
