/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Fri Apr 13 20:50:24 2018. */

#include "floor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TempSet_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, TempSet, zone_1, zone_1, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, TempSet, zone_2, zone_1, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, TempSet, zone_3, zone_2, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, TempSet, zone_4, zone_3, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, TempSet, zone_5, zone_4, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, TempSet, zone_6, zone_5, 0),
    PB_LAST_FIELD
};

const pb_field_t State_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, State, temp1, temp1, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, State, temp2, temp1, 0),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, State, tempSet, temp2, &TempSet_fields),
    PB_FIELD(  4, MESSAGE , REQUIRED, STATIC  , OTHER, State, tempActual, tempSet, &TempSet_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(State, tempSet) < 65536 && pb_membersize(State, tempActual) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_TempSet_State)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(State, tempSet) < 256 && pb_membersize(State, tempActual) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_TempSet_State)
#endif


/* @@protoc_insertion_point(eof) */
